### ISSUE TITLE
Not work in 10.10.5

### ISSUE THREAD

**Issue by martin-liu** [untoldwind/alfred2-layout#10]
Thanks for wrote this tool! :+1: 

But it not works in my mac with OSX version 10.10.5, and alfred2-layout version 1.2/1.3

Below is detail info:
1. When debug in alfred, it says:  
   ```Can't call method "position" on unblessed reference at layout.pl line 229```

2. There's error in syslog:
   ``` 
AppleEvents: Send port for process has no send right, port=( port:16911/0x420f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
```

3. I found that `findMainWindow` returns a SCALAR(`SCALAR(0x7fa5120089c0)`) but not a reference. 

I don't know how to fix it. Can you help to fix this issue?

**Comment by untoldwind** [comment]
Hi,

Luckily I still have a reserve MacBook that is still on Yosemite, have to upgrade it to 10.10.5 though, so it will take a bit to reproduce this problem.

In the meantime:
1. This sounds like a permission problem. Maybe you have to reenable the UI-Scripting permission for Alfred. You'll find this in System Preference/Security/Privacy/Accessibility "Alfred 2" has to be on the list and checked.
2. The most current version (https://github.com/untoldwind/alfred2-layout/raw/master/Layout.alfredworkflow) should be still compatible with 10.10. So maybe you can try this one, it would make debugging a bit easier.

**Comment by martin-liu** [comment]
@untoldwind 
cool! The most current version **works**!!
really appreciate you for developing this tool and so kind to help me :beers:
