### ISSUE TITLE
Workflow malfunctions on certain website

### ISSUE THREAD

**Issue by homever** [untoldwind/alfred2-layout#11]
I tried to resize the browser window when surfing [this website](http://steamcn.com/forum.php), but none of the resize actions worked....
Confirmed in Safari/Chrome/Firefox, layout ver. 1.4
FYI, the previous version worked flawlessly.

**Comment by untoldwind** [comment]
Funny story:
* Forgot to toggle of debug in the release
* Debug writes the the window title to syslog (i.e. console)
* syslog does not work with wide-strings (which happens for kanji, chinese etc)

Or in short: Just another encoding problem ... 25 years after the unicode and we still have these issues.

Anyway: 1.5 and bleeding edge version should fix this

**Comment by homever** [comment]
> 25 years after the unicode and we still have these issues.
We all share similar experiences.

Confirmed this issues has been tackled in 1.5
Um, you may need to push the latest version to Packal too. Thank you.
