### ISSUE TITLE
Not work in 10.11.4

### ISSUE THREAD

**Issue by Jarvin-Guan** [untoldwind/alfred2-layout#12]
# **  I got exception when i debug it**
Starting debug for 'Layout'

[ERROR: alfred.workflow.action.script] given is experimental at layout.pl line 274.
when is experimental at layout.pl line 275.
when is experimental at layout.pl line 281.
when is experimental at layout.pl line 291.
when is experimental at layout.pl line 311.
when is experimental at layout.pl line 349.
when is experimental at layout.pl line 373.
Can't call method "position" on unblessed reference at layout.pl line 247.

**Comment by untoldwind** [comment]
Hi,

have you found the cause for this problem?
My best guess is that UI automation has been disabled for Alfred during the update. If that's case I think I should handle the error properly (e.g. display an allertbox or something)

**Comment by Jarvin-Guan** [comment]
@untoldwind  

Hello,

I found the problem i was meeted is alfred have not enough permission to handle windows.
So ,you should setting below:

![wechat_1463297778](https://cloud.githubusercontent.com/assets/7955822/15272660/cab37200-1ab2-11e6-8719-33f0db48dbac.jpeg)

I hope it can help you

**Comment by untoldwind** [comment]
Yes, thanks ...

I'll try to create a more obvious error message for this case.
