### ISSUE TITLE
Does this workflow support version alfred 3 ?

### ISSUE THREAD

**Issue by ianjohnspain** [untoldwind/alfred2-layout#13]
hi,

Layout has become one of my most used workflows and I was considering updating alfred to version 3 but will this workflow still work ?

Thanks

**Comment by untoldwind** [comment]
Had no time to check this yet. Will update to Alfred next week or so

**Comment by ianjohnspain** [comment]
Well good news is I tried it and it seems to work. Not sure if need to do anything specific but it seems to be working with v3

**Comment by untoldwind** [comment]
As I see it the workflow still works with alfred3.
The only thing one has to keep in mind is, to give "Alfred 3" permission for "Accessibility" in the System Preferences.

**Comment by frankiejun** [comment]
The only thing one has to keep in mind is, to give "Alfred 3" permission for "Accessibility" in the System Preferences.

**Comment by frankiejun** [comment]
thank you
