### ISSUE TITLE
The minimize feature

### ISSUE THREAD

**Issue by niices** [untoldwind/alfred2-layout#14]
Can you add the minimize feature :)

**Comment by untoldwind** [comment]
You mean, minimize the current window?
Have to check the APIs, should be somehow possible IMHO

**Comment by niices** [comment]
yes, can you add this feature to the workflow?:)

**Comment by untoldwind** [comment]
I'll take a look over the weekend

**Comment by niices** [comment]
thanks _(:з」∠)_

**Comment by untoldwind** [comment]
Actually it was quiet easy (just boiled down to finding the correct attribute on the window object):

You can give this version a try, if it works as intended I'll push it to pakal as well:
https://github.com/untoldwind/alfred2-layout/raw/master/Layout.alfredworkflow

**Comment by niices** [comment]
I'm sorry for Yesterday's gone to some businesses. I tried it, but it doesn't work on fullscreen mode yet.
![image](https://cloud.githubusercontent.com/assets/8327775/17836468/8955688e-67c6-11e6-92fd-a0df14e03e5b.png)

**Comment by untoldwind** [comment]
Well, strickly speaking windows in fullstcreen cannot be minimized.
I tweaked the workflow, so that fullscreen windows will be first de-fullscreen-ed and than minimized.
Not sure how stable this is, though.

**Comment by niices** [comment]
thank you! it's work. you can close this issue now:)

**Comment by untoldwind** [comment]
Uploaded the new version to packal.
