### ISSUE TITLE
Can not run on macos mojave...

### ISSUE THREAD

**Issue by twoCleaner** [untoldwind/alfred2-layout#23]
Below is Error Message. I've tried to fix, but not familiar with Perl and macos's System Event.

[2018-09-27 16:24:26][ERROR: action.script] given is experimental at layout.pl line 274.
when is experimental at layout.pl line 275.
when is experimental at layout.pl line 281.
when is experimental at layout.pl line 289.
when is experimental at layout.pl line 299.
when is experimental at layout.pl line 319.
when is experimental at layout.pl line 357.
when is experimental at layout.pl line 381.
**** ERROR **** PerlObjCBridge:: sendObjcMessage: Can't get NSMethodSignature for message "get"
**** ERROR **** PerlObjCBridge: error [1] sending message [NSObject get] at /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/PerlObjCBridge.pm line 248.

**Comment by resoursa** [comment]
Same to me. Will you update script?

**Comment by wahyd4** [comment]
I found this https://github.com/pawelgrzybek/div workflow works for mojave but doesn't support multiple screens. 

Probably there is something we can learn from.

**Comment by untoldwind** [comment]
Unluckily I currently do not have an access to a Mac any more.

**Comment by josefglatz** [comment]
> I found this https://github.com/pawelgrzybek/div workflow works for mojave but doesn't support multiple screens.
> 
> Probably there is something we can learn from.

It uses AppleScript. Let's have a look. I will try my best. Btw. @untoldwind or would like to arrange a online meeting where you can debug it remotely on one of my macs? A pair programming session for example?

**Comment by melbow** [comment]
Now fixed for Mojave - could others please verify?

**Comment by resoursa** [comment]
> Now fixed for Mojave - could others please verify?

error

Starting debug for 'Layout'

[2019-02-19 13:15:15][STDERR: input.scriptfilter] Using legacy path for layout options: /Users/resoursa/Library/Application Support/Alfred 2/Workflow Data/de.leanovate.alfred.layout/layouts.yaml
[2019-02-19 13:15:19][ERROR: action.script] given is experimental at layout.pl line 274.
when is experimental at layout.pl line 275.
when is experimental at layout.pl line 281.
when is experimental at layout.pl line 289.
when is experimental at layout.pl line 299.
when is experimental at layout.pl line 319.
when is experimental at layout.pl line 357.
when is experimental at layout.pl line 381.
**** ERROR **** PerlObjCBridge:: sendObjcMessage: Can't get NSMethodSignature for message "get"
**** ERROR **** PerlObjCBridge: error [1] sending message [NSObject get] at /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/PerlObjCBridge.pm line 248.

**Comment by melbow** [comment]
Thanks for checking - I wasn't aware that the workflow file also needs updating, which resulted in the old script being copied to the install folder.

@untoldwind I've opened a new pull request for this which should fix that problem

**Comment by resoursa** [comment]
> Thanks for checking - I wasn't aware that the workflow file also needs updating, which resulted in the old script being copied to the install folder.
> 
> @untoldwind I've opened a new pull request for this which should fix that problem

Could you send me updated file for checking? resoursa ET gmail.com

**Comment by resoursa** [comment]
> > Thanks for checking - I wasn't aware that the workflow file also needs updating, which resulted in the old script being copied to the install folder.
> > @untoldwind I've opened a new pull request for this which should fix that problem
> 
> Could you send me updated file for checking? resoursa ET gmail.com

Yeah! I confirm that it works properly! Awesome!

**Comment by beeldr** [comment]
Well done! 

If anyone is interested, https://spectacleapp.com is in my opinion a better version of layout. Found it on the webz after layout died on me.

**Comment by josefglatz** [comment]
> Well done!
> 
> If anyone is interested, https://spectacleapp.com is in my opinion a better version of layout. Found it on the webz after layout died on me.

But you can't add custom sizes pixelbased with Spectacleapp or Divvy or ...
That's why this workflow is so amazing :)

**Comment by josefglatz** [comment]
AWESOME! I can also confirm it's working!!!!!! Thank you folks!

**Comment by untoldwind** [comment]
Merged the new bundle

**Comment by skylerwshaw** [comment]
@untoldwind, the Packal page for this workflow is still serving a version of this workflow without the Mojave fix (https://github.com/untoldwind/alfred2-layout/pull/25).

Additionally there's an out of date section of the page with:
```
Important

This only works if you have UI scripting enabled: Graphic User Interface (GUI) Scripting
```

This can be changed to reflect the [changes in Mojave](https://discussions.apple.com/thread/8290071?answerId=33055298022#33055298022). Perhaps change this line to:
```
Important

This workflow only works if Alfred is included in the list of Accessibility applications, which can be found under System Preferences > Security & Privacy > Privacy > Accessibility
```

I believe we can close this issue once Packal is updated. Cheers!

**Comment by untoldwind** [comment]
The pakal UI is pretty unintuitive, hopefully I update the text and the workflow file correctly. Please check.

**Comment by skylerwshaw** [comment]
It's updated. This issue can be closed. 👍 Thanks for looking into that!
