### ISSUE TITLE
[FEATURE] Set frontmost window to often used predefined dimensions

### ISSUE THREAD

**Issue by jousch** [untoldwind/alfred2-layout#6]
e.g. `1280x720` oder `1920x1080` if you'r going to record a screencast.

cheers

**Comment by untoldwind** [comment]
I'm not doing that many screencast ;)
So just to understand this right: You want a quick command to to resize the main window to a fixed pixel-based size (720p, 1080p, ...) and move it to the center of the screen?

ATM: The resize works entirely with relative screen-coordinates, should be possible nevertheless.

**Comment by jousch** [comment]
Thx for your prompt answer!

Exactly, instead of a relative size it should resize to e.g. 720, 1080. The movement to the screen is not necessary, because often you have your notes or tasks near to the recordarea anyway.
I’ve tried on my own, but I didn’t find a nice solution to implement absolute px values.

Would be nice if that get into the workflow.

cheers

**Comment by untoldwind** [comment]
This week was quite busy and I had get used to perl again ;)

Anyway, I think the current version contains what you are looking for.
"lay 720p" -> resize current window to 1280x720
"lay 1080p" -> resize current window to 1920x1080

The window is not moved unless it would go beyond the screen.

**Comment by jousch** [comment]
Many many thanks! That is awesome! I will try it as soon as possible.

Von meinem iPhone gesendet

**Comment by jousch** [comment]
Thank you once more! Great!
