### ISSUE TITLE
[SUGGESTION] Stable releases at packal.org

### ISSUE THREAD

**Issue by jousch** [untoldwind/alfred2-layout#7]
What about sharing this nice workflow at packal.org. With it, it is easily for everyone (maybe someone, who did not use e.g. git) to update this workflow.

**Comment by untoldwind** [comment]
Ok, I was not aware of that site yet.

Thanks, I'll look into it over the weekend

**Comment by untoldwind** [comment]
It's now online:
http://www.packal.org/workflow/alfred2-layout
