### ISSUE TITLE
El Capitan

### ISSUE THREAD

**Issue by rawlik** [untoldwind/alfred2-layout#9]
The windows do not span on the whole screen, when the automatic hiding of the menu bar is on. When using multiple displays, this seems to affect only the main one. On the other screen the windows are maximized properly.

**Comment by untoldwind** [comment]
Sound a bit like the same cause as this one https://github.com/eczarny/spectacle/issues/414
I suppose NSScreen.visibleFrame returns the wrong dimensions in this case.

I'll try to reproduce this once I'm back at a machine with El Capitan AND multi-screen.

**Comment by untoldwind** [comment]
This problem obviously also occures with a single screen. And - as predicted - NSScreen.visibleFrame does not change when menubar is set to autohide.

If there is no other way I'll just have to check with
defaults read NSGlobalDomain _HIHideMenuBar
if autohide is on or off and fix the dimensions by myself

**Comment by untoldwind** [comment]
The current Head-Version should fix this problem:
https://github.com/untoldwind/alfred2-layout/raw/master/Layout.alfredworkflow

Have to check if its still working with Yosemite though

**Comment by untoldwind** [comment]
Just created a new release.
Works for El Capitan as well as Yosemite
